[versions]
checkstyle = "14.3.0"
google-java-format = "1.36.1"
jacoco = "0.8.15"
junit = "4.13.2"
mockito = "5.24.0"
spotbugs = "4.10.4"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }

[plugins]
spotbugs = { id = "com.github.spotbugs", version = "6.5.12" }
spotless = { id = "com.diffplug.spotless", version = "8.10.3" }
